name: Roger Voter
favicon: null
layout_spectrum: 0.18732
typography_spectrum: 0.84915
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Roger Taliento Voter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242b31'
    - '#000000'
    - '#eff2f7'
    - '#a96d5d'
    - '#bdaaa4'
  brandStrength: 0.0625
  lightness: 0.6875
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
