name: Roger Taliento Voter
favicon: null
layout_spectrum: 0.8490692619234324
typography_spectrum: 0.7956867807079107
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4307889265473932
  lightness: 0.292888407362625
  saturation: 0.694395913509652
  rhythmicContrast: 0.7828722172416747
purpose: []
